language: java
jdk:
  - oraclejdk8
sudo: false
before_install:
  - nvm install 0.12
  - nvm use 0.12
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
install:
  - npm install
  - mvn clean test
before_script: grunt build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
cache:
  directories:
    - $HOME/.m2
    - $HOME/.nvm
